Repository mao-wfs/mao-45m, pull requests merged in 2025-10, with the labels that each got.

#32 Fix type (str → bytes) in cosmos submodule
  mao_45m/cosmos.py
Labels: bug

#25 Update subref.converter sub-module
  mao_45m/subref/convert.py
Labels: feature

#34 Update subref.control submodule
  mao_45m/epl/convert.py
  mao_45m/subref/control.py
  mao_45m/subref/convert.py
Labels: feature

#38 Update subref.control submodule
  mao_45m/cosmos.py
  mao_45m/subref/control.py
  mao_45m/subref/convert.py
  mao_45m/utils.py
Labels: feature

#40 Add logging to subref subpackage
  mao_45m/subref/control.py
  mao_45m/subref/convert.py
  mao_45m/utils.py
Labels: feature

#42 Release v0.3.0
  mao_45m/__init__.py
  pyproject.toml
  uv.lock
Labels: release

#44 Fix UDP multicast socket
  README.md
  mao_45m/__init__.py
  mao_45m/vdif/receive.py
  pyproject.toml
  uv.lock
Labels: bug, release

#46 Add option for control duration
  mao_45m/__init__.py
  mao_45m/subref/control.py
  mao_45m/subref/convert.py
  pyproject.toml
  uv.lock
Labels: feature, release

#59 Add faster implementation of get_samples
  mao_45m/__init__.py
  mao_45m/subref/control.py
  mao_45m/vdif/convert.py
  pyproject.toml
  uv.lock
Labels: feature, release
